### ISSUE TITLE
Получение rtsp ссылки на камеры.

### ISSUE THREAD

**Issue by Lordhmen** [hoolea/intersvyaz_hass#2]
Здравствуйте, подскажите пожалуйста, возможно ли как то после добавления камер в Home Assistant получать rtsp ссылки эти камер? У меня нет отдельного монитора под HA, но стоит монитор который выводит камеры с видеорегистратора. Хотелось бы добавить в него камеру еще с домофона.

**Comment by hoolea** [comment]
Здравствуйте, возможность есть, но поток камеры передается по протоколу hls, я попробую сделать конвертацию в rtsp, так как на телефоне видео не работает.

**Comment by hoolea** [comment]
Добавил в логи полученные URL. Прочитать можно следующим образом: 
1. Зайти в интеграцию.
2. Нажать "Начать отладку".
3. Перезагрузить интеграцию.
4. Остановить отладку.
В полученных логах будут URL, которые сможем сконвертировать в rtsp через /homeassistant/configuration.yaml

```
ffmpeg:

camera:
  - platform: ffmpeg
    name: "My RTSP Stream"
    input: "https://cdn.cams.is74.ru/hls/playlists/multivariant.m3u8?uuid=<your_uuid>&realtime=1&token=bearer-<your_token>"
    extra_arguments: "-f rtsp -rtsp_transport tcp rtsp://localhost:8554/my_stream"
```

После перезагрузки конфигурации сразу добавится камера с rtsp потоком, к которой можно будет подключиться с другого устройства, в тч с видеорегестратора.
